### ISSUE TITLE
I want to know how to get user attributes using this library.

### ISSUE THREAD

**Issue by makutamoto** [dferber90/aws-cognito-next#7]
Hi there,

Thank you for creating such a useful library.
I am stuck fetching user attributes because the library cannot get information not provided by a JWT token.
Is there any solution?

**Comment by dferber90** [comment]
Can you show how you'd do it without this library? I'm not sure which attributes you're talking about.

Note that official support for Next.js from AWS itself is on the way (see https://github.com/dferber90/aws-cognito-next/issues/4, and https://github.com/aws-amplify/amplify-js/issues/5435).

At the moment I'm waiting for that to land before deciding the future steps and role of `aws-cognito-next`, so I doubt I'll add any functionality at the moment.

**Comment by makutamoto** [comment]
Thank you for your response.
```javascript
cognitoUser.getUserAttributes(function(err, result) {
    if (err) {
        alert(err.message || JSON.stringify(err));
        return;
    }
    for (i = 0; i < result.length; i++) {
        console.log(
            'attribute ' + result[i].getName() + ' has value ' + result[i].getValue()
        );
    }
});
```
quoted from https://www.npmjs.com/package/amazon-cognito-identity-js, use case 5

I want to do the above kind of things to get user attribute, 'preferred_username'.
So I want to get a cognitoUser or equivalent from useAuth().
Is there any way to accomplish that?

**Comment by dferber90** [comment]
I dug around and it seems like that function is using their API (https://github.com/aws-amplify/amplify-js/blob/794c1da170cd98d3def4651751b851f28810bb6e/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1151-L1181). This seems like something you could build yourself.

I haven't actively used this package since first publishing it since the project I built it for got delayed. So my memory of this package is a bit faded. You might be able to do this more easily once the official Next.js support is released (https://github.com/aws-amplify/amplify-js/issues/5435).

I'm sorry I'm not more helpful. This package is in a weird state as I'm awaiting the official release so the direction this package is headed becomes clearer.

**Comment by makutamoto** [comment]
I managed to solve my problem!

And I found a better way to accomplish that.
If Auth is configured to request profile scope, idTokenData becomes to have preferred_name and other user attributes.
Finally I used it to solve the problem.

Your advice was very helpful to solve the problem.
Thank you!

**Comment by dferber90** [comment]
Awesome :) Wish I could have pointed you in that direction right away. I'll know for next time!
